spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dana
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  # 초기 데이터베이스 등록
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/init.sql

#logging:
#  level:
#    root: debug

jwt:
  # dana_project_jwt_temporary_secret_key
  secret: ZGFuYV9wcm9qZWN0X2p3dF90ZW1wb3JheV9zZWNyZXRfa2V5Xwo=